"""Constants for Hyperion integration."""

CONF_AUTH_ID = "auth_id"
CONF_CREATE_TOKEN = "create_token"
CONF_INSTANCE = "instance"
CONF_INSTANCE_CLIENTS = "INSTANCE_CLIENTS"
CONF_ON_UNLOAD = "ON_UNLOAD"
CONF_PRIORITY = "priority"
CONF_ROOT_CLIENT = "ROOT_CLIENT"
CONF_EFFECT_HIDE_LIST = "effect_hide_list"
CONF_EFFECT_SHOW_LIST = "effect_show_list"

DEFAULT_NAME = "HyperHDR"
DEFAULT_ORIGIN = "Home Assistant"
DEFAULT_PRIORITY = 128

DOMAIN = "hyperhdr"

HYPERION_MANUFACTURER_NAME = "HyperHDR"
HYPERION_MODEL_NAME = f"{HYPERION_MANUFACTURER_NAME}"
HYPERION_RELEASES_URL = "https://github.com/awawa-dev/HyperHDR/releases"
HYPERION_VERSION_WARN_CUTOFF = "20.0.0.0"

SIGNAL_INSTANCE_ADD = f"{DOMAIN}_instance_add_signal.{{}}"
SIGNAL_INSTANCE_REMOVE = f"{DOMAIN}_instance_remove_signal.{{}}"
SIGNAL_ENTITY_REMOVE = f"{DOMAIN}_entity_remove_signal.{{}}"

NAME_SUFFIX_HYPERION_LIGHT = ""
NAME_SUFFIX_HYPERION_PRIORITY_LIGHT = "Priority"
NAME_SUFFIX_HYPERION_COMPONENT_SWITCH = "Component"
NAME_SUFFIX_HYPERION_CAMERA = ""

TYPE_HYPERION_CAMERA = "hyperhdr_camera"
TYPE_HYPERION_LIGHT = "hyperhdr_light"
TYPE_HYPERION_PRIORITY_LIGHT = "hyperhdr_priority_light"
TYPE_HYPERION_COMPONENT_SWITCH_BASE = "hyperhdr_component_switch"

TYPE_HYPERION_SENSOR_BASE = "hyperhdr_sensor"
TYPE_HYPERION_SENSOR_VISIBLE_PRIORITY = "visible_priority"